robot:
  # Publish all joint states --------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10.0, i: 0.1, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 250.0, i: 50.0, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 50, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 100.0, i: 50.0, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 10.0, i: 0.1, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 1.0, i: 0.1, d: 0.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_7
    pid: {p: 0.1, i: 0.1, d: 0.0}
